### ISSUE TITLE
How to obtain the ground truth albedo for the fine facial images?

### ISSUE THREAD

**Issue by zhipeng-fan** [xiaoxingzeng/DF2Net#3]
In order to use the SFS loss, we seem to need both the SH coefficients and the ground truth albedos. How could we obtain them? It seems to me that you guys used 2 other networks to estimate the albedo for the 2D image dataset and then the SH coefficients are obtained from optimizing equation 4 in your paper. Did you do the same thing on the CACD dataset to obtain those numbers? Thanks!

**Comment by xiaoxingzeng** [comment]
@zhipeng-fan Thanks for your interesting, we use the previous method: [https://github.com/senguptaumd/SfSNet](url) SfSNet to get the ground truth albedos of images from CACD and 5K another collected from internet.  Our SfS Loss related code are availabel [https://github.com/xiaoxingzeng/DF2Net_SfS_Computing](url)
