### ISSUE TITLE
About DNet

### ISSUE THREAD

**Issue by ava-YangL** [xiaoxingzeng/DF2Net#5]
Hi  Xiaoxing,
When I use the DNet code you released to train my model, the 3D face I get is not smooth, as shown in the figure below.
![image](https://user-images.githubusercontent.com/33688725/71656841-fbf95100-2d77-11ea-925e-f7fccfbe9911.png)

The depth value of my 3D face is about 0 to 300, and the image size is 512 * 512. I wonder if you have regularized the depth value during training. 
Could you please tell me the range of your depth value or give me some suggestions.
Looking forward to hearing from you. Thanks.

**Comment by xiaoxingzeng** [comment]
Hi Yang , thanks for your interest. The range of depth value is [0, 1], actually we got the image-depth pairs with the code from https://talhassner.github.io/home/publication/2014_MVAP.  In additional, You can add a smooth term.
