### ISSUE TITLE
Albedo resolution

### ISSUE THREAD

**Issue by jacksoncsy** [xiaoxingzeng/DF2Net#6]
Hello Xiaoxing,

Thanks a lot for the amazing work!
Regarding the ground truth albedo map, it seems that the SfSNet code to which you referred only provides output of size 128x128, whereas your network input is 512x512... 
So I wonder, did you retrain SfSNet on larger image, or you just simply upsample the prediction from off-the-shelf SfSNet?

Many thanks,
Shiyang

**Comment by xiaoxingzeng** [comment]
Hi Shiyang thanks for your intrest . To get the ground-truth albedo map, I just simply upsample the prediction from off-the-shelf SfSNet.
