### ISSUE TITLE
About error heat map

### ISSUE THREAD

**Issue by hangon666** [xiaoxingzeng/DF2Net#7]
Hello, thanks for great work.
I 'm wondering how to do the experiments about comparison of error heat maps between two 3D meshes like Figure 8  in your paper.
Could you give me some advice? Thanks a lot !!!

**Comment by kuangcy1998** [comment]
I also want to ask how to draw error heatmaps between two 3D meshes, can you give an explanation or example code? Thanks!

**Comment by xiaoxingzeng** [comment]
Hi @hangon666 @kuangcy1998 , the error heatmaps is computed by predicted depth map and GT. In Fig8, the mesh is just to show the shape we reconstruct.
