### ISSUE TITLE
Regarding the pre-trained models

### ISSUE THREAD

**Issue by yunfan0621** [xiaoxingzeng/DF2Net#8]
Hi Xiaoxing,

Thank you for releasing the code and pre-trained models. I am wondering are you planning to release the model of FNet and FrNet? It seems that only the pre-trained DNet has been released according to demo.py.

Best regards

**Comment by xiaoxingzeng** [comment]
Hi yunfan, thanks for your interest, our released model include all D-Net, F-Net and Fr-Net. https://pan.baidu.com/s/1-CuHbM6nyWNVV_PanRRfLQ?errno=0&errmsg=Auth%20Login%20Sucess&&bduss=&ssnerror=0&traceid=
